// common/dto/CollectorCreationDTO.java
package com.wastecollect.common.dto;

import com.wastecollect.common.utils.CollectorStatus;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public class CollectorCreationDTO {
	@NotBlank(message = "First name is required")
	private String firstName;
	@NotBlank(message = "Last name is required")
	private String lastName;
	@NotBlank(message = "Email is required")
	@Email(message = "Invalid email format")
	private String email;
	@NotBlank(message = "Password is required")
	@Size(min = 6, message = "Password must be at least 6 characters long")
	private String password;
	@NotBlank(message = "Phone number is required")
	private String phoneNumber;
	private String address;
	@NotNull(message = "Status is required")
	private CollectorStatus status;
	@NotBlank(message = "Municipality name is required")
    private String municipalityName;

	// Note: collectorId is not part of this DTO as it's generated by the backend

	// Constructors
	public CollectorCreationDTO() {
	}

	public CollectorCreationDTO(String firstName, String lastName, String email, String password, String phoneNumber,
			String address, CollectorStatus status, String municipalityName) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.status = status;
		this.municipalityName = municipalityName;
	}

	// Getters and Setters
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public CollectorStatus getStatus() {
		return status;
	}

	public void setStatus(CollectorStatus status) {
		this.status = status;
	}

    public String getMunicipalityName() {
		return municipalityName;
	}

	public void setMunicipalityName(String municipalityName) {
		this.municipalityName = municipalityName;
	}
}
